name: Streamlit App Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10.7'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install streamlit
    - name: Deploy to Streamlit
      run: streamlit run Web-App-Cloud.py